# Markdown report rendering helpers.

import json
from datetime import datetime


# Returns a small visual marker for risk labels.
def risk_icon(risk: str) -> str:
    risk = str(risk).lower()

    if risk in ("critical", "high"):
        return "🔴"

    if risk in ("medium", "med"):
        return "🟡"

    if risk == "low":
        return "🟢"

    return "⚪"


# Renders scan report data as Markdown text.
def render_report(data: dict) -> str:
    summary = data.get("summary", {})
    devices = data.get("devices", [])
    ai = data.get("ai_analysis", {})

    lines = []

    lines.append("# 🛡️ AutoMap Scan Report")
    lines.append("")
    lines.append(f"**Target Range:** `{data.get('target', 'unknown')}`")
    lines.append("")
    lines.append(f"**Generated:** `{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}`")
    lines.append("")
    lines.append(f"**Scan Mode:** `{str(data.get('mode', 'unknown')).title()}`")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📊 Executive Summary")
    lines.append("")
    lines.append("| Metric | Detail |")
    lines.append("| --- | --- |")
    lines.append(f"| **Devices Discovered** | {summary.get('devices_scanned', 0)} |")
    lines.append(f"| **Total Open Ports** | {summary.get('open_ports_found', 0)} |")
    lines.append(f"| **Network Posture** | {risk_icon(ai.get('network_posture', 'unknown'))} {str(ai.get('network_posture', 'unknown')).title()} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 🤖 AI Security Analysis")
    lines.append("")
    lines.append("> [!IMPORTANT]")
    lines.append(f"> **Summary:** {ai.get('summary', 'AI analysis was not enabled or did not return a summary.')}")
    lines.append(">")

    recommendations = ai.get("recommendations", [])
    if recommendations:
        lines.append("> **Key Recommendations:**")
        for index, recommendation in enumerate(recommendations, start=1):
            lines.append(f"> {index}. {recommendation}")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📡 Network Inventory")
    lines.append("")

    if not devices:
        lines.append("_No devices were discovered in this scan._")
        lines.append("")

    for device in devices:
        ip = device.get("ip", "unknown")
        mac = device.get("mac", "unknown")
        ports = device.get("open_ports", [])

        highest_risk = "low"
        if any(port.get("risk") in ("critical", "high") for port in ports):
            highest_risk = "high"
        elif any(port.get("risk") in ("medium", "med") for port in ports):
            highest_risk = "medium"

        lines.append(f"### 📍 Device: `{ip}`")
        lines.append("")
        lines.append(f"* **MAC Address:** `{mac}`")
        lines.append(f"* **Status:** {risk_icon(highest_risk)} {highest_risk.title()}")
        lines.append("")

        if not ports:
            lines.append("_No open ports found._")
            lines.append("")
            lines.append("---")
            lines.append("")
            continue

        lines.append("| Port | Service | Risk | Notes |")
        lines.append("| --- | --- | --- | --- |")

        for port in ports:
            risk = port.get("risk", "unknown")
            lines.append(
                f"| {port.get('port', '')} | "
                f"{port.get('service', 'Unknown')} | "
                f"{risk_icon(risk)} {str(risk).title()} | "
                f"{str(port.get('protocol', 'tcp')).upper()} service detected |"
            )

        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## 🛠️ Technical Appendix")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(data, indent=2))
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by AutoMap*")

    return "\n".join(lines)
